// packages/vue/example/src/components/MissionCard.vue
<template>
    <button
        type="button"
        @click="$emit('click')"
        :class="[
            'group w-full text-left rounded-2xl border bg-white transition-all duration-200 cursor-pointer overflow-hidden',
            isCompleted
                ? 'border-slate-200 opacity-70'
                : 'border-slate-200 hover:border-indigo-300 hover:shadow-[0_4px_20px_-4px_rgba(99,102,241,0.18)]',
        ]"
    >
        <div class="p-5">
            <div class="flex items-start gap-4">
                <!-- Icon -->
                <div
                    :class="[
                        'flex size-11 shrink-0 items-center justify-center rounded-xl shadow-sm [&>svg]:size-6',
                        isCompleted ? 'bg-slate-100' : 'bg-white border border-slate-200 group-hover:border-indigo-200',
                    ]"
                    v-html="icon"
                />

                <!-- Content -->
                <div class="flex-1 min-w-0">
                    <div class="flex items-start justify-between gap-2">
                        <h3 :class="['font-semibold leading-snug', isCompleted ? 'text-slate-400 line-through' : 'text-slate-800']">
                            {{ mission.name }}
                        </h3>
                        <span v-if="isCompleted" class="shrink-0 inline-flex items-center gap-1 text-xs font-semibold text-emerald-600 bg-emerald-50 border border-emerald-200 px-2.5 py-1 rounded-full">
                            <span>✓</span> Done
                        </span>
                        <span v-else-if="isPending" class="shrink-0 inline-flex items-center gap-1.5 text-xs font-semibold text-amber-600 bg-amber-50 border border-amber-200 px-2.5 py-1 rounded-full">
                            <span class="size-1.5 rounded-full bg-amber-400 animate-pulse" />
                            Review
                        </span>
                    </div>

                    <p v-if="mission.description" class="mt-1 text-sm text-slate-400 line-clamp-2 leading-relaxed">
                        {{ mission.description }}
                    </p>

                    <div class="mt-3 flex items-center gap-3 flex-wrap">
                        <!-- Frequency -->
                        <span class="inline-flex items-center gap-1 text-xs text-slate-400">
                            <span>🔁</span>
                            {{ FREQUENCY_LABELS[mission.frequency] ?? mission.frequency }}
                        </span>

                        <!-- Rewards -->
                        <template v-for="r in mission.rewards" :key="r.id">
                            <span v-if="r.type === 'currency' && r.currency" class="inline-flex items-center gap-1 text-xs font-semibold text-amber-600 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-full">
                                🪙 {{ currencyAmount(r.config) }} {{ r.currency.symbol ?? r.currency.name }}
                            </span>
                            <span v-else-if="r.type === 'multiplier'" class="inline-flex items-center gap-1 text-xs font-semibold text-violet-600 bg-violet-50 border border-violet-200 px-2 py-0.5 rounded-full">
                                ⚡ {{ multiplierValue(r.config) }}x
                            </span>
                        </template>
                    </div>
                </div>

                <!-- Arrow -->
                <span v-if="!isCompleted" class="shrink-0 self-center text-slate-300 group-hover:text-indigo-400 group-hover:translate-x-0.5 transition-all text-sm">
                    →
                </span>
            </div>
        </div>
    </button>
</template>

<script setup lang="ts">
import { computed } from "vue";
import type { Mission, MissionSubmission, MissionFrequency } from "@loyalops/vue";
import { MISSION_TYPE_ICONS } from "../utils/mission-icons";

const props = defineProps<{
    mission: Mission;
    submission?: MissionSubmission;
}>();

defineEmits<{ click: [] }>();

const FREQUENCY_LABELS: Record<MissionFrequency, string> = {
    once: "One-time",
    hourly: "Hourly",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
};

const isCompleted = computed(() => props.submission?.status === "approved");
const isPending = computed(() => props.submission?.status === "pending");
const icon = computed(() => MISSION_TYPE_ICONS[props.mission.type] ?? "");

const currencyAmount = (config: unknown) => (config as { amount?: number } | null)?.amount;
const multiplierValue = (config: unknown) => (config as { value?: number } | null)?.value;
</script>

// packages/react-native/example/components/loyalops/MissionCard.tsx
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import type { Mission, MissionSubmission, MissionFrequency } from '@loyalops/react-native';
import { getMissionTypeIcon } from '@/utils/mission-helpers';

const FREQUENCY_LABELS: Record<MissionFrequency, string> = {
    once: 'One-time',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
};

interface Props {
    mission: Mission;
    submission?: MissionSubmission;
    onClick: () => void;
}

export function MissionCard({ mission, submission, onClick }: Props) {
    const isCompleted = submission?.status === 'approved';
    const isPending = submission?.status === 'pending';

    return (
        <TouchableOpacity
            onPress={onClick}
            activeOpacity={0.75}
            style={[styles.card, isCompleted && styles.cardCompleted]}
        >
            <View style={styles.row}>
                {/* Icon */}
                <View style={[styles.iconBox, isCompleted && styles.iconBoxCompleted]}>
                    <Text style={styles.iconText}>{getMissionTypeIcon(mission.type)}</Text>
                </View>

                {/* Content */}
                <View style={styles.content}>
                    <View style={styles.titleRow}>
                        <Text
                            style={[styles.title, isCompleted && styles.titleCompleted]}
                            numberOfLines={1}
                        >
                            {mission.name}
                        </Text>
                        {isCompleted && (
                            <View style={styles.doneBadge}>
                                <Text style={styles.doneBadgeText}>✓ Done</Text>
                            </View>
                        )}
                        {isPending && (
                            <View style={styles.pendingBadge}>
                                <Text style={styles.pendingBadgeText}>Review</Text>
                            </View>
                        )}
                    </View>

                    {mission.description ? (
                        <Text style={styles.description} numberOfLines={2}>
                            {mission.description}
                        </Text>
                    ) : null}

                    <View style={styles.meta}>
                        <Text style={styles.frequency}>
                            🔁 {FREQUENCY_LABELS[mission.frequency] ?? mission.frequency}
                        </Text>

                        {mission.rewards?.map((r) => {
                            if (r.type === 'currency' && r.currency) {
                                const amount = (r.config as { amount: number })?.amount;
                                return (
                                    <View key={r.id} style={styles.rewardPill}>
                                        <Text style={styles.rewardPillText}>
                                            🪙 {amount} {r.currency.symbol ?? r.currency.name}
                                        </Text>
                                    </View>
                                );
                            }
                            if (r.type === 'multiplier') {
                                const cfg = r.config as { value: number } | null;
                                return (
                                    <View key={r.id} style={styles.multiplierPill}>
                                        <Text style={styles.multiplierPillText}>⚡ {cfg?.value}x</Text>
                                    </View>
                                );
                            }
                            return null;
                        })}
                    </View>
                </View>

                {!isCompleted && <Text style={styles.arrow}>›</Text>}
            </View>
        </TouchableOpacity>
    );
}

const styles = StyleSheet.create({
    card: {
        borderRadius: 16,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#e2e8f0',
        backgroundColor: '#fff',
        padding: 16,
    },
    cardCompleted: {
        opacity: 0.7,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    iconBox: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    iconBoxCompleted: {
        backgroundColor: '#f1f5f9',
        borderColor: '#e2e8f0',
    },
    iconText: {
        fontSize: 18,
    },
    content: {
        flex: 1,
        gap: 4,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    title: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: '#1e293b',
        lineHeight: 20,
    },
    titleCompleted: {
        color: '#94a3b8',
        textDecorationLine: 'line-through',
    },
    doneBadge: {
        backgroundColor: '#ecfdf5',
        borderWidth: 1,
        borderColor: '#a7f3d0',
        borderRadius: 99,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    doneBadgeText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#059669',
    },
    pendingBadge: {
        backgroundColor: '#fffbeb',
        borderWidth: 1,
        borderColor: '#fde68a',
        borderRadius: 99,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    pendingBadgeText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#d97706',
    },
    description: {
        fontSize: 13,
        color: '#94a3b8',
        lineHeight: 18,
    },
    meta: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 6,
        marginTop: 4,
    },
    frequency: {
        fontSize: 12,
        color: '#94a3b8',
    },
    rewardPill: {
        backgroundColor: '#fffbeb',
        borderWidth: 1,
        borderColor: '#fde68a',
        borderRadius: 99,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    rewardPillText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#d97706',
    },
    multiplierPill: {
        backgroundColor: '#f5f3ff',
        borderWidth: 1,
        borderColor: '#ddd6fe',
        borderRadius: 99,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    multiplierPillText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#7c3aed',
    },
    arrow: {
        fontSize: 20,
        color: '#cbd5e1',
        alignSelf: 'center',
    },
});
